# Generated by Django 4.2.11 on 2024-07-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0005_alter_review_options_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='av_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
